services:
  # PostgreSQL database for production
  db_prod:
    image: postgres:latest
    container_name: prod-postgres-rezervacka
    env_file: .env.production
    ports:
      - '5432:5432'
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - internal_network_rezervacie

  # Next.js app for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-rezervacka
    env_file: .env.production
    ports:
      - '3000:3000'
    depends_on:
      - db_prod
    networks:
      - internal_network_rezervacie

volumes:
  db_data_prod:

networks:
  internal_network_rezervacie:
    name: oz-rezervacie
    external: true
