services:
  # PostgreSQL database for development
  db_dev:
    image: postgres:latest
    container_name: dev-postgres-rezervacka
    env_file: .env.development
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

  # PostgreSQL database for production
  db_prod:
    image: postgres:latest
    container_name: prod-postgres-rezervacka
    env_file: .env.production
    ports:
      - "5432:5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - app_network

  # Next.js app for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-rezervacka
    env_file: .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db_prod
    networks:
      - app_network

volumes:
  db_data_dev:
  db_data_prod:

networks:
  app_network:
